package cn.xdl.ovls.exam.entity;

import java.util.Date;

public class PaperScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.Id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.total_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.my_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer myScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.start_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.end_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_score.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.Id
     *
     * @return the value of paper_score.Id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.Id
     *
     * @param id the value for paper_score.Id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.total_score
     *
     * @return the value of paper_score.total_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.total_score
     *
     * @param totalScore the value for paper_score.total_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.my_score
     *
     * @return the value of paper_score.my_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getMyScore() {
        return myScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.my_score
     *
     * @param myScore the value for paper_score.my_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setMyScore(Integer myScore) {
        this.myScore = myScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.start_time
     *
     * @return the value of paper_score.start_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.start_time
     *
     * @param startTime the value for paper_score.start_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.end_time
     *
     * @return the value of paper_score.end_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.end_time
     *
     * @param endTime the value for paper_score.end_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.paper_id
     *
     * @return the value of paper_score.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.paper_id
     *
     * @param paperId the value for paper_score.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_score.user_id
     *
     * @return the value of paper_score.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_score.user_id
     *
     * @param userId the value for paper_score.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}