package cn.xdl.ovls.exam.entity;

public class PaperQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.question_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.question_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer questionScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.paper_id
     *
     * @return the value of paper_question.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.paper_id
     *
     * @param paperId the value for paper_question.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.question_id
     *
     * @return the value of paper_question.question_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.question_id
     *
     * @param questionId the value for paper_question.question_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.question_score
     *
     * @return the value of paper_question.question_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.question_score
     *
     * @param questionScore the value for paper_question.question_score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setQuestionScore(Integer questionScore) {
        this.questionScore = questionScore;
    }
}