package cn.xdl.ovls.exam.entity;

import java.util.Date;

public class PaperExamReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.report_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.error_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer errorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.right_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer rightNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.submit_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.create_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_exam_report.content
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.report_id
     *
     * @return the value of paper_exam_report.report_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.report_id
     *
     * @param reportId the value for paper_exam_report.report_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.user_id
     *
     * @return the value of paper_exam_report.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.user_id
     *
     * @param userId the value for paper_exam_report.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.paper_id
     *
     * @return the value of paper_exam_report.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.paper_id
     *
     * @param paperId the value for paper_exam_report.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.error_num
     *
     * @return the value of paper_exam_report.error_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getErrorNum() {
        return errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.error_num
     *
     * @param errorNum the value for paper_exam_report.error_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setErrorNum(Integer errorNum) {
        this.errorNum = errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.right_num
     *
     * @return the value of paper_exam_report.right_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getRightNum() {
        return rightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.right_num
     *
     * @param rightNum the value for paper_exam_report.right_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setRightNum(Integer rightNum) {
        this.rightNum = rightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.score
     *
     * @return the value of paper_exam_report.score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.score
     *
     * @param score the value for paper_exam_report.score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.submit_time
     *
     * @return the value of paper_exam_report.submit_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.submit_time
     *
     * @param submitTime the value for paper_exam_report.submit_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.create_time
     *
     * @return the value of paper_exam_report.create_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.create_time
     *
     * @param createTime the value for paper_exam_report.create_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_exam_report.content
     *
     * @return the value of paper_exam_report.content
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_exam_report.content
     *
     * @param content the value for paper_exam_report.content
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}