package cn.xdl.ovls.exam.entity;

import java.util.Date;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.type_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.subject_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.limit_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer limitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.createtime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.begintime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.endtime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.status
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.question_total
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer questionTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.name
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_id
     *
     * @return the value of paper.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_id
     *
     * @param paperId the value for paper.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.type_id
     *
     * @return the value of paper.type_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.type_id
     *
     * @param typeId the value for paper.type_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.user_id
     *
     * @return the value of paper.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.user_id
     *
     * @param userId the value for paper.user_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.subject_id
     *
     * @return the value of paper.subject_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.subject_id
     *
     * @param subjectId the value for paper.subject_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.score
     *
     * @return the value of paper.score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.score
     *
     * @param score the value for paper.score
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.limit_time
     *
     * @return the value of paper.limit_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getLimitTime() {
        return limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.limit_time
     *
     * @param limitTime the value for paper.limit_time
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setLimitTime(Integer limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.createtime
     *
     * @return the value of paper.createtime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.createtime
     *
     * @param createtime the value for paper.createtime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.begintime
     *
     * @return the value of paper.begintime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.begintime
     *
     * @param begintime the value for paper.begintime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.endtime
     *
     * @return the value of paper.endtime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.endtime
     *
     * @param endtime the value for paper.endtime
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.status
     *
     * @return the value of paper.status
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.status
     *
     * @param status the value for paper.status
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.question_total
     *
     * @return the value of paper.question_total
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getQuestionTotal() {
        return questionTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.question_total
     *
     * @param questionTotal the value for paper.question_total
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setQuestionTotal(Integer questionTotal) {
        this.questionTotal = questionTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.name
     *
     * @return the value of paper.name
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.name
     *
     * @param name the value for paper.name
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}