package cn.xdl.ovls.exam.entity;

public class PaperKnowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.knowledge_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer knowledgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_knowledge.question_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer questionNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.id
     *
     * @return the value of paper_knowledge.id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.id
     *
     * @param id the value for paper_knowledge.id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.paper_id
     *
     * @return the value of paper_knowledge.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.paper_id
     *
     * @param paperId the value for paper_knowledge.paper_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.knowledge_id
     *
     * @return the value of paper_knowledge.knowledge_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.knowledge_id
     *
     * @param knowledgeId the value for paper_knowledge.knowledge_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_knowledge.question_num
     *
     * @return the value of paper_knowledge.question_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getQuestionNum() {
        return questionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_knowledge.question_num
     *
     * @param questionNum the value for paper_knowledge.question_num
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setQuestionNum(Integer questionNum) {
        this.questionNum = questionNum;
    }
}