package cn.xdl.ovls.exam.entity;

public class QuestionWithBLOBs extends Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.body
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.analysis
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private String analysis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.body
     *
     * @return the value of question.body
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.body
     *
     * @param body the value for question.body
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.analysis
     *
     * @return the value of question.analysis
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.analysis
     *
     * @param analysis the value for question.analysis
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }
}