package cn.xdl.ovls.exam.entity;

public class QuestionKnowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_knowledge.Id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_knowledge.question_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_knowledge.knowledge_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    private Integer knowledgeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.Id
     *
     * @return the value of question_knowledge.Id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.Id
     *
     * @param id the value for question_knowledge.Id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.question_id
     *
     * @return the value of question_knowledge.question_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.question_id
     *
     * @param questionId the value for question_knowledge.question_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_knowledge.knowledge_id
     *
     * @return the value of question_knowledge.knowledge_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public Integer getKnowledgeId() {
        return knowledgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_knowledge.knowledge_id
     *
     * @param knowledgeId the value for question_knowledge.knowledge_id
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public void setKnowledgeId(Integer knowledgeId) {
        this.knowledgeId = knowledgeId;
    }
}