package cn.xdl.ovls.exam.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.xdl.ovls.exam.entity.PaperExamRecord;

public class PaperExamRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_exam_record
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String insertSelective(PaperExamRecord record) {
        BEGIN();
        INSERT_INTO("paper_exam_record");
        
        if (record.getRecordId() != null) {
            VALUES("record_id", "#{recordId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getPaperId() != null) {
            VALUES("paper_id", "#{paperId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            VALUES("question_id", "#{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getAnswer() != null) {
            VALUES("answer", "#{answer,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_exam_record
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String updateByPrimaryKeySelective(PaperExamRecord record) {
        BEGIN();
        UPDATE("paper_exam_record");
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getPaperId() != null) {
            SET("paper_id = #{paperId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            SET("question_id = #{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getAnswer() != null) {
            SET("answer = #{answer,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("record_id = #{recordId,jdbcType=INTEGER}");
        
        return SQL();
    }
}