package cn.xdl.ovls.exam.dao;

import cn.xdl.ovls.exam.entity.QuestionKnowledge;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface QuestionKnowledgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    @Delete({
        "delete from question_knowledge",
        "where Id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    @Insert({
        "insert into question_knowledge (Id, question_id, ",
        "knowledge_id)",
        "values (#{id,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
        "#{knowledgeId,jdbcType=INTEGER})"
    })
    int insert(QuestionKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    @InsertProvider(type=QuestionKnowledgeSqlProvider.class, method="insertSelective")
    int insertSelective(QuestionKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    @Select({
        "select",
        "Id, question_id, knowledge_id",
        "from question_knowledge",
        "where Id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="Id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="question_id", property="questionId", jdbcType=JdbcType.INTEGER),
        @Result(column="knowledge_id", property="knowledgeId", jdbcType=JdbcType.INTEGER)
    })
    QuestionKnowledge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    @UpdateProvider(type=QuestionKnowledgeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(QuestionKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    @Update({
        "update question_knowledge",
        "set question_id = #{questionId,jdbcType=INTEGER},",
          "knowledge_id = #{knowledgeId,jdbcType=INTEGER}",
        "where Id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(QuestionKnowledge record);
}