package cn.xdl.ovls.exam.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.xdl.ovls.exam.entity.QuestionKnowledge;

public class QuestionKnowledgeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String insertSelective(QuestionKnowledge record) {
        BEGIN();
        INSERT_INTO("question_knowledge");
        
        if (record.getId() != null) {
            VALUES("Id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            VALUES("question_id", "#{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getKnowledgeId() != null) {
            VALUES("knowledge_id", "#{knowledgeId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_knowledge
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String updateByPrimaryKeySelective(QuestionKnowledge record) {
        BEGIN();
        UPDATE("question_knowledge");
        
        if (record.getQuestionId() != null) {
            SET("question_id = #{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getKnowledgeId() != null) {
            SET("knowledge_id = #{knowledgeId,jdbcType=INTEGER}");
        }
        
        WHERE("Id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}