package cn.xdl.ovls.exam.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.xdl.ovls.exam.entity.QuestionOptions;

public class QuestionOptionsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String insertSelective(QuestionOptions record) {
        BEGIN();
        INSERT_INTO("question_options");
        
        if (record.getOptionId() != null) {
            VALUES("option_id", "#{optionId,jdbcType=INTEGER}");
        }
        
        if (record.getQuestionId() != null) {
            VALUES("question_id", "#{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getOptionName() != null) {
            VALUES("option_name", "#{optionName,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_options
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String updateByPrimaryKeySelective(QuestionOptions record) {
        BEGIN();
        UPDATE("question_options");
        
        if (record.getQuestionId() != null) {
            SET("question_id = #{questionId,jdbcType=INTEGER}");
        }
        
        if (record.getOptionName() != null) {
            SET("option_name = #{optionName,jdbcType=VARCHAR}");
        }
        
        WHERE("option_id = #{optionId,jdbcType=INTEGER}");
        
        return SQL();
    }
}