package cn.xdl.ovls.exam.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import cn.xdl.ovls.exam.entity.QuestionType;

public class QuestionTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String insertSelective(QuestionType record) {
        BEGIN();
        INSERT_INTO("question_type");
        
        if (record.getTypeId() != null) {
            VALUES("type_id", "#{typeId,jdbcType=INTEGER}");
        }
        
        if (record.getTypeName() != null) {
            VALUES("type_name", "#{typeName,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Tue Mar 27 08:40:00 CST 2018
     */
    public String updateByPrimaryKeySelective(QuestionType record) {
        BEGIN();
        UPDATE("question_type");
        
        if (record.getTypeName() != null) {
            SET("type_name = #{typeName,jdbcType=VARCHAR}");
        }
        
        WHERE("type_id = #{typeId,jdbcType=INTEGER}");
        
        return SQL();
    }
}